name: '🚀 CI Build Android App'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: reactnativecommunity/react-native-android
    steps:
      - name: 📚 Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci
      # Run lints after building ci is configured 
      # - name: Run all lints
      #   run: npm run lint
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "$(( secrets.EXPO_TOKEN ))" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: $(( secrets.EXPO_TOKEN ))

      - name: Build on EAS
        run: eas build --profile preview -p android --local --non-interactive
